server:
  port: 9000

spring:
  application:
    name: shop
  datasource:
    url: jdbc:postgresql://localhost:5432/CategoriesDatabase
    username: 'postgres'
    password: 'china.123'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    defer-datasource-initialization: true
  sql:
    init:
      mode: always